// <auto-generated/>
#pragma warning disable 1591
namespace Demo
{
    #line hidden
    using System;
    using System.Threading.Tasks;
    internal class index : Microsoft.Extensions.RazorViews.BaseView
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("<ul>\r\n");
#line 2 "index.cshtml"
     for (int i = 0; i < 5; i++)
    {

#line default
#line hidden
            WriteLiteral("        <li>第");
#line 4 "index.cshtml"
         Write(i + 1);

#line default
#line hidden
            WriteLiteral("行</li>\r\n");
#line 5 "index.cshtml"
    }

#line default
#line hidden
            WriteLiteral("</ul>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
